name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    # Paso 2: Instalar kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Paso 3: Configurar kubeconfig
    - name: Setup kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    # Paso 4: Verificar conexión con el clúster
    - name: Verify cluster connection
      run: |
        kubectl config current-context
        kubectl get nodes

    # Paso 5: Desplegar Angular
    - name: Deploy Angular
      run: |
        kubectl apply -f k8s/angular-deployment.yaml

    # Paso 6: Desplegar Spring Boot
    - name: Deploy Spring Boot
      run: |
        kubectl apply -f k8s/springboot-deployment.yaml

    # Paso 7: Esperar a que los pods estén listos
    - name: Wait for pods to be ready
      run: |
        kubectl wait --for=condition=ready pod -l app=angular --timeout=120s
        kubectl wait --for=condition=ready pod -l app=springboot --timeout=120s

    # Paso 8: Mostrar el estado
    - name: Show deployment status
      run: |
        kubectl get deployments
        kubectl get services